### ISSUE TITLE
[l10n-web] New Hello page at mozilla.org in bn-BD

### ISSUE THREAD

**Issue by bellayet** [mozillabd/community#4]
## Goal:

Complete bn-BD translations for new Hello page at mozilla.org.
## Success:

https://www.mozilla.org/firefox/hello/ page in Bangla (Bangladesh).
## Related Issues & Links:

[Reference meta issues and past issues] #
https://groups.google.com/forum/#!topic/mozilla.dev.l10n.web/OjfzjKX-0ns
## Roles:

Owner: 
Involved: 
## Required:
- [x] Complete the translations (Belayet, [medium], Due: ) 
- [x] Updated Hello page live in mozilla.org (owner, [small], Due: )

**Comment by maktrix** [comment]
Let us set a milestone for this task. We can easily estimate how many strings are there and how many man hour needed to translate.

**Comment by anistuhin** [comment]
Update guys @maktrix and @bellayet vai where are we with this one :)

**Comment by bellayet** [comment]
Done.
Here is bn-BD page: https://www.mozilla.org/bn-BD/firefox/hello/
