### ISSUE TITLE
Responsibilities of FSAs and Firefox Clubs in BD

### ISSUE THREAD

**Issue by sunnat629** [mozillabd/community#8]
**Responsibilities of FSAs:**
- Respect the each other.
-  new FSAs will take help from the Lead regarding Mozilla’s contribution areas and get uptodate about Mozilla.
- Participate in every event of their club
- Participate in the FSA’s challenges, campaign and activities. 
- Participate in other Mozilla’s open events like, Firefox OS, SuMo, QA, l10n etc and report to the Lead. 
- Contribute regularly in Mozilla’s Missions

**Responsibilities of Clubs and Club Leads:**
- Take permission from the University’s authority to open a Firefox Club (**New Clubs and Club Leads**)
- If need any permission letter then he/she can collect this letter from RAL or E-Board (**New Clubs and Club Leads**)
- Fix a date to organize an orientation event where RAL, Senior FSAs and/or other important Senior Mozillians/Reps can join to motivate them to contribute and teach them about the Mozilla’s mission and FSA activities. (**New Clubs and Club Leads**)
- Next step will be very important for the Leads (**Old and new**). This time he/she has to recruits new FSA and help them to become active in this program. Besides, he/she will help them how to contribute in mozilla’s various functional areas like, Firefox OS, SuMo, QA, l10n, MDN etc. He will contact with the RAL and local reps(or senior mozillians) who are responsible for these functional areas and the FSAs will be monitored by them. So that the FSAs will find a right track to contribute in Mozilla. 
- Club leads and active FSAs have to organize some events regarding FSA’s monthly challenges, activities and Mozilla’s campaign in every month. RAL, Reps will help to organize these with a proper plan, budget, swags and agendas. 
  - It can be a big event with 50+ FSAs
  - It can be a small meeting with 10-15 FSAs
  - It can be only the lead and the co-leads (Active FSAs of that particular club)
- Every month within 5th day of that month, the Lead has to report to the local RAL. Report can be:
  - a summery blog of all events on that month or individual blog for every event. This blog has to be written by the Club Lead
  - Individual blog for every event. This can be written by other FSAs
  - Flickr link
  - Every month he/she will give Information about at least 2 unique active FSAs name. That means. A lead has to work hard to recruit at least 2 active FSAs. So that the club will remain active. 
  - Even any of the FSA of that particular Club, join to any other Mozilla’s event, it also consider as activeness. 
- A Lead should handover his/her successor Lead at least 5 months before he/she complete the University and mentoring and help the Lead to be a good lead for the club.
  - **Recommend for the future Lead:** Who has at least 4 semesters left.

**Comment by maktrix** [comment]
How and why "**Respect the Lead**" can be one of the _FSA_ Responsibilities. I believe putting this statement within a set of rules **intimidating**; putting this statement in very beginning of a long list of rules is intentional, an act of discrimination, seeding inequality in the community; and totally opposite of **Mozillia** values.

I request to all persons, involved in this whatsoever activity, please remove these kind of words and statements from the above set of rules.

**Comment by sunnat629** [comment]
@maktrix Bhai, Here I put **Respect the Lead**, because, some FSAs don't care about the club. They don't give reports to the Lead regarding their Mozillian activities.

Ok, if this is confusing, I am modifying this this.
Thanks for the advice..

**Comment by anistuhin** [comment]
Why a lead should have 5 semesters in hand to be recommended? I mean 5 semesters means almost one and a half years here, right?? Explain a bit may be?? And also How far I am aware, a lead is valid for 6 months. So, If the ex-lead should mentor him to be a good lead for 5 months, how come he should selected as a lead. He should already be familiar with good and healthy club practices in the previous lead term, right??

**Comment by sunnat629** [comment]
I mentioned the 4/5 semesters in hand because that FSA will be a senior FSA(not about the badge) and he will understand the FSA program and can control the Junior and new comers as well as the Club. If a Junior will become FSA Lead, then it might be little bit tough for him to control the club. 

The new Lead mentoring means when a new Lead take over the club, he/she will be the responsible for the club. There are some rules and regulation for a Club Lead, so the new Lead can easily know and learn about these with the help of  the ex-lead, besides RAL will be there all the time. 

I mentioned 6 months, because, if the ex-lead feels that the new lead is not capable for the post, he can suggest him to handover the Lead to another FSA who will be more capable for this post. 

About the choose of Lead, of course, he will have to well known in the club, contributing in mozilla for many days, have to have knowledge about FSA program. 

But, one thing is really important. Though I mentioned that Lead has to be a senior, but it's not mandatory. If a younger FSA is doing fantastic works for his/her club and mozilla, have a good knowledge about this program, know how to Leading a team, He can be a FSA LEAD.  Besides, If ex-Lead is biased and select a person who is not capable from others, then the FSA can inform to the RAL about this. Or if the current Lead is not active for his/her personal or professional or for Study, and so if the club become inactive, then RAL can suggest him to handover to other.

**Comment by anistuhin** [comment]
Yeah, I got all your points :) But I think you didn't understand what I just asked. Looks like you are agreeing with me but you wrote the sentence wrong. You should write like this:
"
- A Lead should handover his/her successor Lead, mentor and help the new Lead to be a good lead for the club any way possible.
  - **Recommend for the future Lead:** Who has been with the club for at least 4 semesters. 

"

**Comment by bellayet** [comment]
I have a suggestion regarding the selection process of a new lead for a club. The process can be like that
- Lead/Club members should propose names of new lead with profiles and list of their involvements to RAL/FSA leads from other clubs.
- RAL/FSA leads from other clubs will prepare a short list based on their profile and club involvement and inform the club lead about the short list.
- RAL/Assigned FSA lead will arrange a small exam/interview each of them who are short listed.
- RAL select a lead based on the exam, the profile and club involvement. Inform the club lead and the selected new lead to make an formal announcement.

The process will reduce chance of biases, reduce chance of select a unfit candidate as a club lead. Also it will increase communication between clubs, RAL and other FSA leads.

**Comment by maktrix** [comment]
Can we replace the followings: 
- important Senior Mozillians/Reps **to** Veteran and Experienced Mozillians / Reps
- can control the Junior **to** Can manage and guide the Juniors
- take over the club **to** Takes over the responsibilities and duties of the Club.

**Comment by fayepal** [comment]
Commenting to bookmark this.
This is an awesome initiative Sunnat, thanks! We can look into creating something like this for a global level, or make this a universal one that can be applied globally. :)

**Comment by sunnat629** [comment]
@maktrix vai, @bellayet vai and @anistuhin , thank you for your help. I will modify those. :)

@fayetandog , extremely thanks for the response. Very soon, I will complete this and let you know. 

Best Regards,
Sunnat...

**Comment by sunnat629** [comment]
@maktrix  vai, @bellayet  vai and @anistuhin , thanks for the suggestions. I will modify these very soon.

@fayetandog , thanks a lot and I am glad that you all are pleased about this. I will provide you after finishing this.
